#!/bin/sh
lock() {
    i3lock
}

case "$1" in
    lock)
        $HOME/.config/i3/scripts/lock $HOME/Pictures/Icons/lock.png
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        $HOME/.config/i3/scripts/lock $HOME/Pictures/Icons/lock.png && systemctl suspend
        ;;
    hibernate)
         $HOME/.config/i3/scripts/lock $HOME/Pictures/Icons/lock.png && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
