#!/usr/bin/env bash
tmpbg="/tmp/screen.png"
scrot "$tmpbg"; corrupter -mag 10 -bheight 15 "$tmpbg" "$tmpbg"

i3lock \
        -t \
        -i "$tmpbg" \
        --timepos='x+110:h-70' \
        --datepos='x+43:h-45' \
        --clock \
        --date-align 1 \
        --datestr "Type password to unlock..." \
        --insidecolor=00000000 \
        --ringcolor=FFFFFFFF \
        --line-uses-inside \
        --keyhlcolor=d23c3dff \
        --bshlcolor=d23c3dff \
        --separatorcolor=00000000 \
        --insidevercolor=00000000 \
        --insidewrongcolor=d23c3dff \
        --ringvercolor=ffffffff \
        --ringwrongcolor=ffffffff \
        --indpos='x+280:h-70' \
        --radius=20 \
        --ring-width=4 \
        --veriftext='' \
        --wrongtext='' \
        --verifcolor="ffffffff" \
        --timecolor="ffffffff" \
        --datecolor="ffffffff" \
        --noinputtext='' \
        --force-clock -n

 rm "$tmpbg"
